contactacontractor/accounts/urls.py
from django.urls import path
from accounts.views import register, user_dashboard, user_profile, become_contractor, new_reply, confirm_quote, job_status, contract_status, contractor_profile
from app.views import submit_dispute, submit_review, view_quotes

app_name = "accounts"
urlpatterns = [
    path('register/', register, name='register'),
    path('dashboard/', user_dashboard, name='user_dashboard'),
    path('contractor/<str:username>', contractor_profile, name='contractor_profile'),
    path('profile/<str:username>', user_profile, name='user_profile'),
    path('dashboard/submit-dispute/<int:job_id>/', submit_dispute, name='submit_dispute'),
    path('dashboard/submit-review/<int:job_id>/', submit_review, name='submit_review'),
    path('dashboard/view-quotes/<int:job_id>/', view_quotes, name='view_quotes'),
    path('become-contractor/', become_contractor, name='become_contractor'),
    path('dashboard/new-reply/<int:message_id>/', new_reply, name='new_reply'),
    path('dashboard/confirm-quote/<int:quote_id>/', confirm_quote, name='confirm_quote'),
    path('dashboard/job-status/<int:job_id>/', job_status, name='job_status'),
    path('dashboard/contract-status/<int:job_id>/', contract_status, name='contract_status')
]

contactacontractor/app/urls.py
from django.urls import path
from .views import new_job, available_jobs, new_message, new_quote

urlpatterns = [
    path('new_job/', new_job, name='new_job'),
    path('available/', available_jobs, name='available_jobs'),
    path('new-message/<int:job_id>', new_message, name='new_message'),
    path('new-quote/<int:job_id>/', new_quote, name='new_quote'),
]

contactacontractor/contactacontractor/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import home, new_job

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('jobs/', include('app.urls')),
    path('accounts/', include('accounts.urls')),
]

contactacontractor/accounts/models.py
from django.db import models

# Create your models here.

contactacontractor/accounts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import User
from app.admin import Account, Job, Quote, Dispute, Message, Rating

def register(request):
    if request.method == "POST":
                username = request.POST.get("username")
                first_name = request.POST.get("first_name")
                last_name = request.POST.get("last_name")
                email = request.POST.get("email")
                password = request.POST.get("password")
                contractor = request.POST.get("contractor")

                user = User.objects.create_user(username = username, password = password, email = email, first_name = first_name, last_name = last_name)
                user.save()

                account = Account(user = user, first_name = first_name, last_name = last_name, balance = 0, contractor = True if contractor == "on" else False)
                account.save()
                return HttpResponseRedirect(
                       redirect_to= '/'
                )
    context = {}
    return render(request, "accounts/register.html", context)

def user_dashboard(request):
    account = Account.objects.get(user = request.user)
    jobs = [job for job in Job.objects.all() if job.user.username == request.user.username]
    messages = [message for message in Message.objects.all() if message.receiver.username == request.user.username]
    your_quotes = [quote for quote in Quote.objects.all() if quote.contractor.username == request.user.username]
    your_job_quotes = [quote for quote in Quote.objects.all() if quote.job.user.username == request.user.username]
    assigned_jobs = [quote.job for quote in Quote.objects.all() if quote.accepted == True and quote.contractor.username == request.user.username and not quote.job.is_completed]
    completed_jobs = Job.objects.filter(user=request.user, is_completed=True)
    completed_Contractor_Jobs = completed_Contractor_Jobs = Job.objects.filter(quote__contractor=request.user, is_completed=True)     
    context = {
          'account': account,
          'jobs': jobs,
          'messages': messages,
          'your_quotes': your_quotes,
          'your_job_quotes': your_job_quotes,
          'assigned_jobs': assigned_jobs,
          'completed_jobs': completed_jobs,
          'completed_Contractor_Jobs': completed_Contractor_Jobs,
          'JOB_STATUS_AVAILABLE': Job.JOB_STATUS_AVAILABLE,
          'JOB_STATUS_ACCEPTED': Job.JOB_STATUS_ACCEPTED,
          'JOB_STATUS_IN_PROGRESS': Job.JOB_STATUS_IN_PROGRESS,
    }
    return render(request, "accounts/user_dashboard.html", context)

def contractor_profile(request, username):
    account = Account.objects.get(user__username=username)
    is_Owner = account.user == request.user

    if(request.method == "POST"):
        form_type = request.POST.get("form_type", None)
        if(form_type == "start_Job"):
            setJobInProgress(request.POST.get("job_id"))
        elif(form_type == "complete_Job"):
            job_id = request.POST.get("job_id")
            setJobComplete(job_id)
            updateContractorBalance(Quote.objects.get(job_id = job_id).id)

    completed_Contractor_Jobs = completed_Contractor_Jobs = Job.objects.filter(quote__contractor=account.user, is_completed=True)
    reviews = Rating.objects.filter(ratee = account.user) 
    
    if(is_Owner):
        assigned_jobs = [quote.job for quote in Quote.objects.all() if quote.accepted == True and quote.contractor.username == request.user.username and not quote.job.is_completed]
        context = {
            'account': account,
            'is_Owner': is_Owner,
            'completed_Contractor_Jobs': completed_Contractor_Jobs,
            'assigned_jobs': assigned_jobs,
            'rating' : calculate_rating(account=account),
            'reviews' : reviews,
            'max_Rating_Range' : range(5),
            'JOB_STATUS_IN_PROGRESS': Job.JOB_STATUS_IN_PROGRESS,
            'JOB_STATUS_ACCEPTED': Job.JOB_STATUS_ACCEPTED,
        }
        return render(request, "accounts/contractor_profile.html", context)
    else:
        context = {
            'account': account,
            'is_Owner': is_Owner,
            'completed_Contractor_Jobs': completed_Contractor_Jobs,
            'rating' : calculate_rating(account=account),
            'reviews' : reviews,
            'max_Rating_Range' : range(5),
        }
        return render(request, "accounts/contractor_profile.html", context)

def user_profile(request, username):
    account = Account.objects.get(user__username=username)
    is_Owner = account.user == request.user
    completed_jobs = [job for job in Job.objects.all() if job.user.username == account.user.username and job.is_completed == True]
    if(is_Owner):
        accepted_jobs = [job for job in Job.objects.all() if job.user.username == request.user.username and job.status == "accepted"]
        context = {
            'account': account,
            'accepted_jobs': accepted_jobs,
            'completed_jobs': completed_jobs,
            'is_Owner': is_Owner,
        }
        return render(request, "accounts/user_profile.html", context)
    else:
        context = {
            'account': account,
            'completed_jobs': completed_jobs,
            'is_Owner': is_Owner,
        }
        return render(request, "accounts/user_profile.html", context)

def become_contractor(request):
    if request.method == "POST":
          account = Account.objects.get(user = request.user)
          account.contractor = True
          account.save()
          return HttpResponseRedirect(
                     redirect_to= '/accounts/dashboard/'
            )
    context = {}
    return render(request, "accounts/become_contractor.html", context)

def new_reply(request, message_id):
      if request.method == "POST":
            sender = request.user
            receiver = Message.objects.get(id = message_id).sender
            text = request.POST.get("message")

            message = Message(sender = sender, receiver = receiver, text = text)
            message.save()

            return HttpResponseRedirect(
                  redirect_to= '/'
            )
      context = {
            'subject': Message.objects.get(id = message_id).sender.username,
      }
      return render(request, 'accounts/new_reply.html', context)

def calculate_rating(account):
    rating = Rating.objects.filter(ratee = account.user)
    total = 0
    for rate in rating:
        total += rate.rating
    if len(rating) == 0:
        return 0
    return round(total / len(rating), 2)

def confirm_quote(request, quote_id):
      if request.method == "POST":
           quote = Quote.objects.get(id = quote_id)
           quote.accepted = True
           quote.job.status = "assigned"
           quote.job.save()
           quote.save()
           return HttpResponseRedirect(
                 redirect_to= '/accounts/dashboard/'
           )
      context = {}
      return render(request, 'accounts/confirm_quote.html', context)

def setJobInProgress(job_id):
    job = Job.objects.get(id = job_id)
    job.status = Job.JOB_STATUS_IN_PROGRESS
    job.save()

def setJobComplete(job_id):
    job = Job.objects.get(id = job_id)
    job.status = Job.JOB_STATUS_COMPLETE
    job.is_completed = True
    job.save()

def updateContractorBalance(quote_id):
    quote = Quote.objects.get(id = quote_id)
    contractor_Account = Account.objects.get(user = quote.contractor)
    contractor_Account.balance += quote.price
    contractor_Account.save()
    
def job_status(request, job_id):
    job = Job.objects.get(id = job_id)
    context = {
        'job': job,
        'JOB_STATUS_AVAILABLE': Job.JOB_STATUS_AVAILABLE,
        'JOB_STATUS_ACCEPTED': Job.JOB_STATUS_ACCEPTED,
        'JOB_STATUS_IN_PROGRESS': Job.JOB_STATUS_IN_PROGRESS,
    }
    return render(request, "accounts/job_status.html", context)

def contract_status(request, job_id):
    job = Job.objects.get(id = job_id)
    context = {
        'job': job,
        'JOB_STATUS_AVAILABLE': Job.JOB_STATUS_AVAILABLE,
        'JOB_STATUS_ACCEPTED': Job.JOB_STATUS_ACCEPTED,
        'JOB_STATUS_IN_PROGRESS': Job.JOB_STATUS_IN_PROGRESS,
    }
    return render(request, "accounts/job_status.html", context)

contactacontractor/accounts/templates/accounts/become_contractor.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'become_contractor.css' %}">
    <h1>Become a contractor!</h1>
    <div id="main">
        <form action="" method="post">
            {% csrf_token %}
            <label for="">Become a contractor: </label>
            <input type="checkbox" name="contractor" id=""> Yes <br>
            <input type="submit" value="Sign Up" id="button">
        </form>
    </div>

{% endblock content %}

contactacontractor/accounts/templates/accounts/confirm_quote.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'confirm_quote.css' %}">

    <h1>Quote Confirmation</h1>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            <label for="">Accept Quote: </label>
            <input type="checkbox" name="accept_quote" id=""> Yes <br>
            <input type="submit" value="Confirm">
        </form>
    </div>
{% endblock content %}

contactacontractor/accounts/templates/accounts/contract_status.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'contract_status.css' %}">

    <h1 style="text-transform: capitalize;">{{ job.title }}'s Status</h1>
    <div id="main">
        {% if job.status == JOB_STATUS_ACCEPTED%}
            <p>Status: Accpeted</p>
        {% elif job.status == JOB_STATUS_AVAILABLE%}
            <p>Status: Available</p>
        {% elif job.status == JOB_STATUS_IN_PROGRESS%}
            <p>Status: In progress</p>
        {% else %}
            <p>Status: Completed</p>
        {% endif %}
    </div>

{% endblock content %}

contactacontractor/accounts/templates/accounts/contractor_profile.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'contractor_profile.css' %}">
<div id="head">

</div>
  {% if account.contractor %}
    <h1 style="text-transform: capitalize;">{{ account.user.username }}'s Contractor Profile</h1>
    <div id="main">
      <h2>Profile Information</h2>
      <p>First Name: {{ account.first_name }}</p>
      <p>Last Name: {{ account.last_name }}</p>
      <p>Email: {{ account.user.email }}</p>
      <p>Rating: {{ rating }}&#9733;</p>
    </div>

    <div id="main">
      <h2 style="text-transform: capitalize;">{{ account.user.username }}'s Reviews</h2>
      {% if reviews %}
        {% for review in reviews %}
          <div style="border: 1px solid rgb(255, 255, 255);" id="table">
            <p>By: {{ review.job.user }}</p>
            <p>
              Rating:{% for i in max_Rating_Range %}
                {% if forloop.counter <= review.rating %}
                  &#9733;
                {% else %}
                  &#9734;
                {% endif %}
              {% endfor %}
            </p>
            <p>{{ review.review }}</p>
          </div>
        {% endfor %}
      {% else %}
        <p>No reviews yet!</p>
      {% endif %}
    </div>

    {% if is_Owner %}
      <div id="main">
        <h2 style="text-transform: capitalize;">{{ account.user.username }}'s Assigned Jobs</h2>
        {% if assigned_jobs %}
          {% for job in assigned_jobs %}
            <form method="post">
              {% csrf_token %}
              <div style="border: 1px solid rgb(255, 255, 255)" id="table">
                <h3 style="text-transform: capitalize;">Title: {{ job.title }}</h3>
                <p style="text-transform: capitalize;">Description: {{ job.description }}</p>
                <p style="text-transform: capitalize;">Job issuer: {{ job.user.username }}</p>
                <p style="text-transform: capitalize;">Location: {{ job.location }}</p>
                <p style="text-transform: capitalize;">Job Type: {{ job.type }}</p>
                <p>Budget: {{ job.budget }} €</p>
                <p style="text-transform: capitalize;">Job Status: {{ job.status }}</p>
                {% if job.status == JOB_STATUS_ACCEPTED %}
                  <input type="submit" name="startJob" value="Start job" id="button"/>
                  <input type="hidden" name="form_type" value="start_Job"/>
                  <input type="hidden" name="job_id" value="{{ job.id }}"/>
                {% endif %}
                {% if job.status == JOB_STATUS_IN_PROGRESS %}
                  <input type="submit" name="completeJob" value="Complete job" id="button"/>
                  <input type="hidden" name="form_type" value="complete_Job"/>
                  <input type="hidden" name="job_id" value="{{ job.id }}" />
                {% endif %}
              </div>
            </form>
          {% endfor %}
        {% else %}
          <p>No assigned jobs yet!</p>
        {% endif %}
      </div>
    {% endif %}

    <div id="main">
      <h2 style="text-transform: capitalize;">{{ account.user.username }}'s Completed Jobs</h2>
      {% if completed_Contractor_Jobs %}
        {% for job in completed_Contractor_Jobs %}
          <div style="border: 1px solid rgb(255, 255, 255)" id="table">
            <h3 style="text-transform: capitalize;">Title: {{ job.title }}</h3>
            <p style="text-transform: capitalize;">Description: {{ job.description }}</p>
            <p style="text-transform: capitalize;">Job issuer: {{ job.user.username }}</p>
            <p style="text-transform: capitalize;">Location: {{ job.location }}</p>
            <p style="text-transform: capitalize;">Job Type: {{ job.type }}</p>
            <p>Budget: {{ job.budget }} €</p>
          </div>
        {% endfor %}
      {% else %}
        <p>No completed jobs yet!</p>
      {% endif %}
    </div>
  {% endif %}
{% endblock %}

contactacontractor/accounts/templates/accounts/job_status.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'job_status.css' %}">
    <h1 style="text-transform: capitalize;">{{ job.title }}'s Status</h1>
    <div id="main">
        {% if job.status == JOB_STATUS_ACCEPTED%}
            <p>Status: Accepted</p>
        {% elif job.status == JOB_STATUS_AVAILABLE%}
            <p>Status: Available</p>
        {% elif job.status == JOB_STATUS_IN_PROGRESS%}
            <p>Status: In progress</p>
        {% else %}
            <p>Status: Completed</p>
        {% endif %}
    </div>

{% endblock content %}

contactacontractor/accounts/templates/accounts/new_reply.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'new_reply.css' %}">

    <h1>Send Message</h1>
    <div id="main">
        <form action="" method="post">
            {% csrf_token %}
            <label for="">To:</label>
            <input type="text" name="" id="" value="{{subject}}" readonly>
            <label for="">Message:</label>
            <input type="text" name="message" id="" required>
            <input type="submit" value="Send Message" id="button">
        </form>
    </div>

{% endblock content %}

contactacontractor/accounts/templates/accounts/register.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'register.css' %}">
<div id="main">
  <form action="" method="post">
    {% csrf_token %}
    <label for="">Username:</label>
    <input type="text" name="username" id="" /> <br />
    <label for="">First Name:</label>
    <input type="text" name="first_name" id="" /> <br />
    <label for="">Last Name:</label>
    <input type="text" name="last_name" id="" /> <br />
    <label for="">Email:</label>
    <input type="email" name="email" id="" /> <br />
    <label for="">Password:</label>
    <input type="password" name="password" id="" /> <br />
    <label for="">Contractor:</label>
    <input type="checkbox" name="contractor" id="" /> <br />
    <input type="submit" value="Register" id="register"/>
  </form>
</div>
{% endblock %}

contactacontractor/accounts/templates/accounts/user_dashboard.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'user_dashboard.css' %}">
 <h1>User Dashboard</h1>
 
 <div id="head">     
    <div id="main">
        <h2>Account Information</h2>
        <p>Username: {{ account.user.username }}</p>
        <p>Email: {{ account.user.email }}</p>
        <p>Balance: {{ account.balance }} €</p>
    </div>
    <div id="main">
        <h2>Your Jobs</h2>
        {% if jobs %}
            {% for job in jobs %}
                <div style="border: 1px solid rgb(255, 255, 255);" id="table">
                    <h3>Title: {{ job.title }}</h3>
                    <p>Description: {{ job.description }}</p>
                    {% if job.is_completed %}
                        {% if not job.is_review_written %}
                            <a href="{% url 'accounts:submit_review' job.id %}">
                                <input type="button" value="Submit Review" id="button">
                            </a>
                            <a href="{% url 'accounts:submit_dispute' job.id %}">
                                <input type="button" value="Submit Dispute" id="button">
                            </a>
                        {% endif %}
                    {% else %}
                        {% if job.status == JOB_STATUS_AVAILABLE %}
                            <a href = "{% url 'accounts:view_quotes' job.id %}">
                                <input type="button" value="View Submited Quotes" id="button">
                            </a>
                        {% endif %}
                    {% endif %}
                    <a href="{% url 'accounts:job_status' job.id %}"><button id="button">View Status</button></a>
                </div>
            {% endfor %}
        {% else %}
            <p>No jobs yet!</p>
        {% endif %}
    </div >
    <div id="main">
        <h2>Your Messages</h2>
        {% if messages %}
            {% for message in messages %}
                <div style="border: 1px solid rgb(255, 255, 255);" id="table">
                    <h3>Sender: {{ message.sender }}:</h3>
                    <p>Message: {{ message.text }}</p>
                    <a href="{% url 'accounts:new_reply' message.id %}"><button id="button">Reply</button></a>
                </div>
            {% endfor %}
        {% else %}
            <p>No messages yet!</p>
        {% endif %}
    </div>
    <br>
    
    {% if not account.contractor %}
        <p id="logout"><a href="{% url 'accounts:become_contractor' %}" id="signUp">Sign up</a> to be a contractor!</p>
    {% endif %}
</div>
{% endblock content %}

contactacontractor/accounts/templates/accounts/user_profile.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'user_profile.css' %}">

    <h1 style="text-transform: capitalize;">{{account.user.username}}'s Profile</h1>
<div id="head">
    <div id="main">
        <h2>Profile Information</h2>
        <p>First Name: {{account.first_name}}</p>
        <p>Last Name: {{account.last_name}}</p>
        <p>Email: {{account.user.email}}</p>
        <p>Click <a href ="../contractor/{{account.user.username}}">here</a> to checkout contractor profile</p>
    </div>
    <div>
        {% if is_Owner %}
            <div id="main">
                <h2 style="text-transform: capitalize;">{{account.user.username}}'s Accepted Jobs</h2>
                {% if accepted_jobs %}
                    {% for job in accepted_jobs %}
                        <div style="border: 1px solid rgb(255, 255, 255)" id="table">
                            <h3 style="text-transform: capitalize;">Title: {{ job.title }}</h3>
                            <p style="text-transform: capitalize;">Description: {{ job.description }}</p>
                            <p style="text-transform: capitalize;">Job issuer: {{ job.user.username }}</p>
                            <p style="text-transform: capitalize;">Location: {{ job.location }}</p>
                            <p style="text-transform: capitalize;">Job Type: {{ job.type }}</p>
                            <p>Budget: {{ job.budget }} €</p>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>No accepted jobs yet!</p>
                {% endif %}
            </div>
        {% endif %}
            <div id="main">
                <h2 style="text-transform: capitalize;">{{account.user.username}}'s Completed Jobs</h2>
                {% if completed_jobs %}
                    {% for job in completed_jobs %}
                        <div style="border: 1px solid rgb(255, 255, 255)" id="table">
                            <h3 style="text-transform: capitalize;">Title: {{ job.title }}</h3>
                            <p style="text-transform: capitalize;">Description: {{ job.description }}</p>
                            <p style="text-transform: capitalize;">Job issuer: {{ job.user.username }}</p>
                            <p style="text-transform: capitalize;">Location: {{ job.location }}</p>
                            <p style="text-transform: capitalize;">Job Type: {{ job.type }}</p>
                            <p>Budget: {{ job.budget }} €</p>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>No completed jobs yet!</p>
                {% endif %}
            </div>
    </div>
    <br>
        {% if is_Owner and not account.contractor %}
            <p id="box"><a href="{% url 'accounts:become_contractor' %}" id="hover">Sign up</a> to be a contractor!</p>
        {% endif %}
</div>
    
{% endblock content %}