contactacontractor/accounts/urls.py
from django.urls import path
from accounts.views import register, user_dashboard, user_profile, become_contractor, new_reply, confirm_quote, job_status, contract_status, contractor_profile
from app.views import submit_dispute, submit_review, view_quotes

app_name = "accounts"
urlpatterns = [
    path('register/', register, name='register'),
    path('dashboard/', user_dashboard, name='user_dashboard'),
    path('contractor/<str:username>', contractor_profile, name='contractor_profile'),
    path('profile/<str:username>', user_profile, name='user_profile'),
    path('dashboard/submit-dispute/<int:job_id>/', submit_dispute, name='submit_dispute'),
    path('dashboard/submit-review/<int:job_id>/', submit_review, name='submit_review'),
    path('dashboard/view-quotes/<int:job_id>/', view_quotes, name='view_quotes'),
    path('become-contractor/', become_contractor, name='become_contractor'),
    path('dashboard/new-reply/<int:message_id>/', new_reply, name='new_reply'),
    path('dashboard/confirm-quote/<int:quote_id>/', confirm_quote, name='confirm_quote'),
    path('dashboard/job-status/<int:job_id>/', job_status, name='job_status'),
    path('dashboard/contract-status/<int:job_id>/', contract_status, name='contract_status')
]

contactacontractor/app/urls.py
from django.urls import path
from .views import new_job, available_jobs, new_message, new_quote

urlpatterns = [
    path('new_job/', new_job, name='new_job'),
    path('available/', available_jobs, name='available_jobs'),
    path('new-message/<int:job_id>', new_message, name='new_message'),
    path('new-quote/<int:job_id>/', new_quote, name='new_quote'),
]

contactacontractor/contactacontractor/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import home, new_job

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('jobs/', include('app.urls')),
    path('accounts/', include('accounts.urls')),
]

contactacontractor/app/templates/app/available_jobs.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'jobs.css' %}">
    <h1>Available Jobs</h1>
    <div id="main">
        {% if not available_jobs %}
            <h3>There are currently no available jobs.</h3>
        {% else %}
            {% for job in available_jobs %}
                {% if job.user != account.user %}
                    <div style="border: 1px solid rgb(255, 255, 255);" id="table">
                        <h4>Title: {{ job.title }}</h4>
                        <p>Description: {{ job.description }}</p>
                        <p>Location: {{ job.location }}</p>
                        <p>Job Type: {{ job.type }}</p>
                        <p>Job Budget: {{ job.budget }} €</p>
                        <p><a href="../../accounts/profile/{{job.user.username}}">{{ job.user.username }}</a></p>
                        {% if account.contractor %}
                            <a href="{% url 'new_quote' job.id %}"><button id="quote">Submit Quote</button></a>
                        {% endif %}
                        <a href="{% url 'new_message' job.id %}"><button id="message">Message User</button></a>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock content %}

contactacontractor/app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Contact-a-Contractor</title>
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
</head>
<body>
    <header>
        <nav>
            <h1>Contact-a-Contractor</h1>
            <ul>
                <li><a href="/">Home</a></li>
                {% if request.user.is_authenticated %}
                    <p id="loggedIn">Logged in: {{ request.user.username }}</p>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% if request.user.is_superuser %}
                        <li><a href="/admin">Admin Dashboard</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:user_dashboard' %}">User Dashboard</a></li>
                        <li><a href="{% url 'accounts:user_profile' request.user.username %}">User Profile</a></li>
                        {% if request.user.account.contractor %}
                            <li><a href="{% url 'accounts:contractor_profile' request.user.username %}">Contractor Profile</a></li>
                        {% endif %}
                        <li><a href="{% url 'available_jobs' %}">Jobs</a></li>
                    {% endif %}
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:register' %}">Register</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}
    
        {% endblock content %}
    </main>
    <footer>
        <p>&copy; 2024 Contact-a-Contractor. All rights reserved.</p>
    </footer>
</body>
</html>

contactacontractor/app/templates/app/home.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">
<div id="main">
    <img src="https://www.fortunebuilders.com/wp-content/uploads/2021/10/Depositphotos_103173498_S-min.jpg" alt="contractor" style="width: 100%; height: 700px; object-fit: cover;" id="image">
    <div id="leftColumn">
        <h1 id="title">CONTACT<br> A<br> CONTRACTOR</h1>
        <h2 id="subtitle">Post a new job!</h2>
        {% if request.user.is_authenticated %}
            <p id="post"><a href="{% url 'new_job' %}" id="link">Post a Job</a></p>
        {% else %}
            <p id="login"><a href="{% url 'login' %}" id="link">Login</a> to post a job</p>
        {% endif %}
    </div>    
</div>
{% endblock content %}

contactacontractor/app/templates/app/new_job.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'new_job.css' %}">
<h1>Post new job</h1>
<div id="main">
    <form action="" method="post">
        {% csrf_token %}
        <label for="">Title: </label>
        <input type="text" name="title" id=""> <br>
        <label for="">Description: </label>
        <input type="text" name="description" id=""> <br>
        <label for="">Location: </label>
        <input type="text" name="location" id=""> <br>
        <div id="type">
            <label for="">Type: </label>
            <input type="checkbox" name="type" id="" value="carpentry"><p>Carpentry &nbsp</p>
            <input type="checkbox" name="type" id="" value="landscaping"><p>Landscaping &nbsp</p>
            <input type="checkbox" name="type" id="" value="plumbing"><p>Plumbing &nbsp</p>
            <input type="checkbox" name="type" id="" value="construction"><p>Construction &nbsp</p>
            <input type="checkbox" name="type" id="" value="roofing"><p>Roofing &nbsp</p>
            <input type="checkbox" name="type" id="" value="masonry"><p>Masonry &nbsp</p>
            <input type="checkbox" name="type" id="" value="demolition"><p>Demolition &nbsp</p>
            <input type="checkbox" name="type" id="" value="plastering"><p>Plastering &nbsp</p>
            <input type="checkbox" name="type" id="" value="painting"><p>Painting &nbsp</p>
            <input type="checkbox" name="type" id="" value="tile and marble setting"><p>Tile and marble setting &nbsp</p>
            <input type="checkbox" name="type" id="" value="hvac"><p>HVAC &nbsp</p>
            <input type="checkbox" name="type" id="" value="electrician"><p>Electrician &nbsp</p>
        </div>
        <label for="">Budget: </label>
        <input type="number" name="budget" id="" min="1"> <br>
        <input type="submit" value="Post" id="post">
    </form>
</div>
{% endblock content %}

contactacontractor/app/templates/app/new_message.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'new_message.css' %}">

    <h1>Send Message</h1>
    <div id="main">
        <form action="" method="post">
            {% csrf_token %}
            <label for="">To:</label>
            <input type="text" name="" id="" value="{{subject}}" readonly>
            <label for="">Message:</label>
            <input type="text" name="message" id="" required>
            <input type="submit" value="Send Message" id="message">
        </form>
    </div>

{% endblock content %}

contactacontractor/app/templates/app/new_quote.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'new_quote.css' %}">
<h1>Submit a quote</h1>
    <div id="main">
     
        <form action="" method="post">
            {%csrf_token%}
            <label for="">Your Quote:</label>
            <input type="number" name="quote" id="" min="0.000000001" required>
            <input type="submit" value="Send Quote" id="quote">
        </form>
    </div>

{% endblock content %}

contactacontractor/app/templates/app/submit_dispute.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'submit_dispute.css' %}">
<h1>Dispute Submission Form</h1>
    <form action="" method="post" id="main">
        {% csrf_token %}
        <p>Write your dispute message:</p>
        <textarea name="dispute" id="dispute" cols="30" rows="10" required></textarea><br>
        <input type="submit" value="Submit" id="button">
    </form>
{% endblock content %}

contactacontractor/app/templates/app/submit_review.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'submit_review.css' %}">
<h1>Submit Your Review</h1>    
    <div class="container" id="main">
        <form action="" method="POST">
            {% csrf_token %}
            <label for="message">Your Review:</label><br>
            <textarea id="message" name="message" rows="4" cols="100" min = "5" max ="200" required></textarea><br><br>
            <label for="rating">Rating (1-5):</label>
            <input type="number" id="rating" name="rating" min="1" max="5" required><br><br>
            <input type="submit" value="Submit Review" id="button">
        </form>
    </div>
{% endblock content %}

contactacontractor/app/templates/app/view_quotes.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'view_quotes.css' %}">
    <h1>Quotes for Your Job</h1>
    <div id="quote">
        {% if quotes %}
            {% for quote in quotes %}
                <div class="quote" style = "border: 1px solid" id="table">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <p>{{ error }}</p>
                        <p><strong>Contractor:</strong> {{ quote.contractor.username }}</p>
                        <p><strong>Quote Amount:</strong> {{ quote.price }} €</p>
                        <input type="submit" name="accept" value="Accept" id="button">
                        <input type="hidden" name="quote_id" value="{{ quote.id }}">
                    </form>
                </div>
            {% endfor %}
        {% else %}
            <p>No quotes yet.</p>
        {% endif %}
    </div>
{% endblock content %}